config/routes.rb
Sketchmine::Application.routes.draw do

  resources :pins

  resources :submit, only: :index

  match '/email' => 'submit#send_email_form', as: :email_form, via: :post

  devise_for :users

  get 'about' => 'pages#about'

  root :to => 'pins#index'

  get 'tags/:tag', to: 'pins#index', as: :tag

end

app/models/message.rb
class Message
	# Remove the inheritance from ActiveRecord::Base (class Message < ActiveRecord::Base)

	# Include ActiveAttr functionality
	include ActiveAttr::Model

	# Include ActiveModel::Validations
	include ActiveModel::Validations

	# Define attributes
	attribute :name
	attribute :email
	attribute :title
	attribute :author
	attribute :author_link
	attribute :download_link
	attribute :image

	# Mass assignment security
	# Whitelist attributes that you want to mass assign user given data to
  	attr_accessible :name, :email, :title, :author, :author_link, :download_link, :image

  	# Validations
  	# Name must be present
  	validates_presence_of :name

  	# Email must be present and valid email format
  	validates_presence_of :email
  	validates :email, email_format: { message: "is not looking like a valid email address"}

  	# Title must be present
  	validates_presence_of :title

  	# Author must be present
  	validates_presence_of :author

  	validates :author_link, presence: true, :format => URI::regexp(%w(http https))
  	validates :download_link, presence: true, :format => URI::regexp(%w(http https))
  	validates :image, presence: true, :format => URI::regexp(%w(http https))


  	
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :title, :author, :author_link, :download_link, :image, :image_remote_url, :tag_list
  acts_as_taggable

  validates :title, presence: true
  validates :author, presence: true
  validates :author_link, presence: true, :format => URI::regexp(%w(http https))
  validates :download_link, presence: true, :format => URI::regexp(%w(http https))
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
  											content_type: { content_type: [ 'image/jpeg', 'image/jpg', 'image/png', 'image/gif' ]},
  											size: { less_than: 5.megabytes }
  validates :tag_list, presence: true

  belongs_to :user
  has_attached_file :image, styles: { medium: "350x260^"},
                    convert_options: { medium: "-gravity center -extent 350x260" }

  def image_remote_url=(url_value)
    self.image=URI.parse(url_value) unless url_value.blank?
    super 
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index] 

  # GET /pins
  # GET /pins.json
  def index

    if params[:tag]
      @pins = Pin.tagged_with(params[:tag]).order("created_at desc").page(params[:page]).per_page(18)
    else
      @pins = Pin.order("created_at desc").page(params[:page]).per_page(18)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/submit_controller.rb
class SubmitController < ApplicationController

  def index
  	@message = Message.new
  end

  def send_email_form
  	@message = Message.new(params[:message])
  	
  	if @message.valid?
  		ContactForm.email_form(@message).deliver
  		redirect_to root_path, notice: "Your .sketch file has been submited. It will be reviewed and posted very soon!"
  	else
  		flash.now.alert = "Submit didn't work. Please check your entries."
  		render :index
  	end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/submit_helper.rb
module SubmitHelper
end

app/views/contact_form/email_form.text.erb
Hey, 

I just got an email from <%= @message.name %> via the contact form on my homepage.

Here it is:

Name: <%= @message.name %>

Email: <%= @message.email %>

Title: <%= @message.title %>

Image: <%= @message.image %>

Author: <%= @message.author %>

Author_link: <%= @message.author_link %>

Download_link: <%= @message.download_link %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="navbar-inner">
    <div class="container">
			footer	
			<%= link_to "Lien", "#" %>
		</div>
	</div>	
</footer>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40728234-1', 'sketchmine.co');
  ga('send', 'pageview');
</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to image_tag("/assets/sketchminelogo.png", :alt => "SketchMine", :class => "brand-icon"), root_path %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
    

				<div class="pull-right">

					<ul class="nav">
	        	<li><%= link_to "about", about_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
            <% end %>
					</ul>
          <div class="btn-group">
            <a href="http://eepurl.com/zDAZf" class="btn btn-large btn-primary newsletter">newsletter</a>
          </div>  
					<div class="btn-group">
            <% if user_signed_in? %>
		          <%= link_to "add", new_pin_path, class: "btn btn-large btn-primary" %>
            <% else %>
              <%= link_to "submit", submit_index_path, class: "btn btn-large btn-primary" %>
            <% end %>
					</div>
				</div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>SketchMine</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <%= favicon_link_tag 'favicon.ico' %>
	  <%= render 'layouts/ga' %>
	</head>
	<body>

		
	<%= render 'layouts/header' %> 

	<div class="container-fluid">
  	<div class="row-fluid	">

  		<%= yield %>
	
		</div>
	</div>


<!-- 	<%= render 'layouts/footer' %>
 -->
	</body>
</html>

app/views/pages/about.html.erb
<h4><strong>What is Sketchmine?</strong></h4>
<h4>Sketchmine is a list of free .sketch files designed by the sketch community.</h4>
<br>
<h4><strong>How can I submit a .sketch file?</strong></h4>
<h4>Click the submit button and fill the requested fields.</h4>
<br>
<h4><strong>Who's behind Sketchmine?</strong></h4>
<h4><a href="http://twitter.com/maximecormier">Maxime Cormier</a>, also behind <a href="http://oocto.com">oocto</a> and <a href="http://folkapp.com">Folk</a>.</h4>
<br>
<h4><strong>How can I get in touch?</strong></h4>
<h4>Just send me an email at maxime@sketchmine.co</h4>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>


  <%= f.input :title %>
  <%= f.input :tag_list, label: "Tags (seperated by commas)" %>
  <%= f.input :image, label: "Preview image" %>
  <%= f.input :image_remote_url, label: "or enter URL" %>
  <%= f.input :author %>
  <%= f.input :author_link %>
  <%= f.input :download_link %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="span4">
	<div class="pin pull-right">
		<div class="pin_image">
	 		<a href=<%= pin.download_link %>>
	 			<%= image_tag pin.image(:medium) %>
	 			<span><b>download</b></span>
	 		</a> 
		</div>

		<div class="pin_description">	
			<h3>
				<%= pin.title %>
		  </h3>
		  <h5>
			  by <%= link_to pin.author, pin.author_link, :target => "_blank" %>
		  </h5>
		 	
		  <% if current_user == pin.user %>
		  	Tags <%= raw pin.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
				<%= link_to 'Show', pin %>
			  <%= link_to 'Edit', edit_pin_path(pin) %>
			  <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
		  <% end %>
		</div>
	</div>
  
</div>

app/views/pins/_sidetag.html.erb
<div class="span2 hidden-phone">
	<div class="tag_nav">
		<%= link_to "Recent", root_path, class: 'tag_list' %>
  	<div id="tag_cloud">
			<% tag_cloud Pin.tag_counts.order("name asc"), %w[s m l] do |tag, tag_list| %>
  			<%= link_to tag.name, tag_path(tag.name), class: "tag_list" %>
			<% end %>
		</div>	
	</div>
	<div class="twitter-share">
	 <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://sketchmine.co/" data-text="Check out Sketchmine, a great collection of free .sketch files" data-via="MaximeCormier">Tweet</a>
	 <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>	
  </div>	
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'sidetag' %>

<div class="span10">
	<div class="row-fluid ">
    <% flash.each do |name, msg| %>
    	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  	<% end %>

		<%= render @pins %>
		
	</div>
	<div class="pagination">
			<%= will_paginate @pins %>
		</div>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= render @pin %>

<%= link_to 'Back', pins_path %>

app/views/submit/index.html.erb
<h1> Submit a .sketch file </h1>

<!-- - flash.each do |name, value|
  p class="#{name}" #{value} -->

<%= simple_form_for(@message, url: email_form_path, html: { class: "form-horizontal"}) do |f| %>
  <%= f.input :name, label: "Your name" %>
  <%= f.input :email, label: "Your email" %>
  <%= f.input :title, label: "Title of the file" %>
  <%= f.input :author, label: "Author's name" %>
  <%= f.input :author_link, label: "Link to author's website, dribble or twitter" %>
  <%= f.input :download_link, label: "Download link" %>
  <%= f.input :image, label: "URL of preview image	" %>

   <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
 <% end %>	